### ISSUE TITLE
I would prefer to have user HOME dir to be the roster dir.

### ISSUE THREAD

**Issue by ypise** [Seagate/cortx-prvsnr#1039]
I would prefer to have user HOME dir to be the roster dir.
@mazinamdar could you confirm if this was addressed in your changes related to destroy.

_Originally posted by @ypise in https://github.com/Seagate/cortx-prvsnr/pull/1025#r598599218_

**Comment by andkononykhin** [comment]
posted a reply in original location https://github.com/Seagate/cortx-prvsnr/pull/1025#discussion_r601846509
