### ISSUE TITLE
Provisioning Prerequisites points to internal Seagate addresses

### ISSUE THREAD

**Issue by ttwalkertt** [Seagate/cortx-prvsnr#149]
A step in prerequisites requires connectivity to an internal Seagate address. This would not be available to the general community. Please move the document to Github and update the link.

4. Miscellaneous:
Connectivity to ci-storage.mero.colo.seagate.com

**Comment by ypise** [comment]
This issue has been addressed in https://github.com/Seagate/cortx/tree/main/doc
