### ISSUE TITLE
Seagate Internal Links

### ISSUE THREAD

**Issue by ttwalkertt** [Seagate/cortx-prvsnr#151]
https://github.com/Seagate/cortx-prvsnr/wiki/In-band-Setup contains links to internal Seagate sites, which would not be available to the community. Please move targets to a publicly accessible place and update the links. Thanks.

Details:
1. Install package scsi-network-relay from ftp://hst.lcd.colo.seagate.com/scsi-network-relay or http://ci-storage.mero.colo.seagate.com/releases/eos/uploads/misc/scsi-network-relay-1.1.0-47.x86_64.rpm

**Comment by ypise** [comment]
Fixed.
