### ISSUE TITLE
Unidentified screen shots in in-band-setup

### ISSUE THREAD

**Issue by ttwalkertt** [Seagate/cortx-prvsnr#152]
https://github.com/Seagate/cortx-prvsnr/wiki/In-band-Setup contains screen shots of a management interface of an unidentified storage system. Please document the source of the screen shots and how/when they would be significant to the community.
See image:  ![image](https://user-images.githubusercontent.com/3143588/88576227-198f5000-d013-11ea-9f2f-0591eb5acf60.png)

 Thanks.

**Comment by ypise** [comment]
Removed the irrelevant page from wiki.
