### ISSUE TITLE
Improvements request for documentation of CORTX auto-deploy for VMs wiki page

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-prvsnr#171]
Improvements request for documentation of CORTX auto-deploy for VMs .

Here are some issues with the steps that I hit following wiki: https://github.com/Seagate/cortx-prvsnr/wiki/Deployment-on-VM_Auto-Deploy

- repo links are stale. Please point to latest release rpms
- certs are not installed on vms, had to run salt-call state.apply components.s3clients, thanks to @Yash Pise for directions
- default ldap creds not mentioned in wiki, 
This helped 
```
ldappasswd=$(salt-call pillar.get openldap:iam_admin:secret --output=newline_values_only)
ldappasswd=$(salt-call lyveutil.decrypt ${ldappasswd} openldap --output=newline_values_only)
```

- Its not clear which drives are used for crtx data and metadata.
Had to lookup lsblk and follow cortx-hare README to bootstrap with required drives.
-  there should be mention of next steps, may to S3 doc on how to configure and run simple tests.
Following helped https://github.com/Seagate/cortx/blob/master/doc/CortxS3ServerQuickStart.md#testing-using-s3cli

cc @priyankdal  @johnbent @ttwalkertt @shailesh-vaidya @ypise

**Comment by ypise** [comment]
The issues with VMs have been addressed and documented on:
https://github.com/Seagate/cortx-prvsnr/wiki/Deployment-on-VM_Auto-Deploy
