### ISSUE TITLE
Prebuilt RPMs available to community

### ISSUE THREAD

**Issue by ttwalkertt** [Seagate/cortx-prvsnr#189]
The setup wiki https://github.com/Seagate/cortx-prvsnr/wiki/Deployment-on-VM_Auto-Deploy contains this link (http://ci-storage.mero.colo.seagate.com/releases/eos/github/release/rhel-7.7.1908/) to the CortX repository with rpms for the deployment script to install. Unfortunately they are not visible outside of the network. Are these build artifacts replicated somewhere in the public GitHub tree?

Thanks.

**Comment by shailesh-vaidya** [comment]
We have releases JBOD and OVA artifacts for community. 

OVA - https://github.com/Seagate/cortx/releases/tag/VA
JBOD - https://github.com/Seagate/cortx/releases/tag/JBOD
