### ISSUE TITLE
Improvements for opensource singlenode VM deploy scripts.

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-prvsnr#210]
Using auto-deploy-vm to setup Singlenode on a VM outside of SSC cloud VMs has number of issues. We should have few improvements that can ease setups.

- Current scripts assume using eth0/eth1/eth2 interfaces and are hardcoded. Suggestion is single node VM should be able to use any network interface available on the system as there no need for private network as all services are running within VM. Also mgmt and data n/w can use same interface as single node VM is mostly for test purposes only.
- So for Single node only option can be (single) network interface that can be used for all logical interfaces.
- -C, -M can be made optional for singlenode as many times community may not have VIPs and wants to test only within VM.
- Help should be updated to clearly define whats option and whats required in singlenode versus dual node/cluster
- Network interface configuration can be optional, since if these interfaces are already available, current scripts override it and causes issues with interfaces.
- There were multiple failures in rabbitmq installation, service not starting due to different minion-id (srvnode-1) vs hostname(srvnode-2), node name can be any and this eventually leads to rabbitmqadmin not found errors. 
- Singlenode VM should have control path states as optional and possibly sync states are not required as there is no cluster.
- Current auto-deploy-vm is not idempotent and does not expose teardown, so on any failure user needs to figure out manual way for clean up by understanding provisioner source. We should be able to fix issues and continue from failure or atleast have teardown so we can rerun.

Thanks to @ypise  for help with queries on provisioner code.

Fixing these issues will help community. cc @johnbent  @ttwalkertt 
@amolkongre  @priyankdal

**Comment by rahuljyoti65** [comment]
deployment using auto_deploy_vm script is now deprecated and it is changed to new method using provisioner cli commands.
Checkout this page for more details: https://github.com/Seagate/cortx-prvsnr/wiki/Auto-Deploy-VM-Provisioner-CLI-Commands
