### ISSUE TITLE
Steps used to setup device for dual node cluster with JBOD

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-prvsnr#230]
Steps used to setup device for dual node cluster with JBOD. 

Scripts can be updated to possibly have `data_disk.list` file with list of data devices and `metadata_disk.list` file with list of devices and input to the script.

Here is sample script used to setup devices.

```
#!/bin/bash

readarray -t srv1_data_disks < node1_data_devices.list
readarray -t srv2_data_disks < node2_data_devices.list
readarray -t srv1_metadata_disks < node1_metadata_devices.list
readarray -t srv2_metadata_disks < node2_metadata_devices.list

function stringify() {
    local disks=(${@})
    local disk_list=''
    for disk in "${disks[@]}"
    do
      disk_list+=\"$disk\",
    done
    disk_list=${disk_list: :-1}
    echo $disk_list
}

srv1_data_disk_list=$(stringify "${srv1_data_disks[@]}")
printf "srv1_data_disk_list = $srv1_data_disk_list\n\n"

srv2_data_disk_list=$(stringify "${srv2_data_disks[@]}")
printf "srv2_data_disk_list = $srv2_data_disk_list\n\n"

srv1_metadata_disk_list=$(stringify "${srv1_metadata_disks[@]}")
printf "srv1_metadata_disk_list = $srv1_metadata_disk_list\n\n"

srv2_metadata_disk_list=$(stringify "${srv2_metadata_disks[@]}")
printf "srv2_metadata_disk_list = $srv2_metadata_disk_list\n\n"

/usr/local/bin/provisioner pillar_set cluster/srvnode-1/storage/metadata_device [$srv1_metadata_disk_list]
/usr/local/bin/provisioner pillar_set cluster/srvnode-1/storage/data_devices [$srv1_data_disk_list]

/usr/local/bin/provisioner pillar_set cluster/srvnode-2/storage/metadata_device [$srv2_metadata_disk_list]
/usr/local/bin/provisioner pillar_set cluster/srvnode-2/storage/data_devices [$srv2_data_disk_list]

salt srvnode-1 pillar.get cluster
```
sample file
```
cat node1_data_devices.list
/dev/disk/by-id/wwn-0x5000c500ade2833f
/dev/disk/by-id/wwn-0x5000c500ae097367
/dev/disk/by-id/wwn-0x5000c500ae09d5f3
```

```
# cat node1_metadata_devices.list 
/dev/disk/by-id/wwn-0x5000c5003015d5e3
```

cc @johnbent  @ttwalkertt 

@ypise  @ipoddubnyy  Can you please help incorporate in provisioner for JBODs?

**Comment by cortx-admin** [comment]
> Board-Genius-Jira commented in Jira Server:

stale commented in Github:

This issue/pull request has been marked as `needs attention` as it has been left pending without new activity for 4 days. Tagging @83bhp @andkononykhin2 for appropriate assignment. Sorry for the delay & Thank you for contributing to CORTX. We will get back to you as soon as possible.

**Comment by cortx-admin** [comment]
> Board-Genius-Jira commented in Jira Server:

stale commented in Github:

This issue/pull request has been marked as `needs attention` as it has been left pending without new activity for 4 days. Tagging @83bhp @andkononykhin2 for appropriate assignment. Sorry for the delay & Thank you for contributing to CORTX. We will get back to you as soon as possible.

**Comment by hessio** [comment]
This user has left Seagate so I am wondering if this issue is still relevant now?

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Is this issue still relevant? [~729494]

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub
