### ISSUE TITLE
components.s3clients.awscli.prepare is missing but referenced in init.sls

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-prvsnr#261]
components.s3clients.awscli.prepare is missing but referenced
https://github.com/Seagate/cortx-prvsnr/blob/dev/srv/components/s3clients/awscli/init.sls#L24

```
[root@smc10-m03 cortxsetup]# salt 'srvnode-1' state.apply components.s3clients
srvnode-1:
    Data failed to compile:
----------
    Specified SLS components.s3clients.awscli.prepare in saltenv base is not available on the salt master or through a configured fileserver
ERROR: Minions returned with non-zero exit code

```
@ypise  @ipoddubnyy 
cc @johnbent @amolkongre

**Comment by rahuljyoti65** [comment]
components.s3clients.awscli.prepare is present and the command **salt 'srvnode-1' state.apply components.s3clients** is running successfully without any error. 
Hence closing this issue.
