### ISSUE TITLE
MTU for public data network should be set to 9000

### ISSUE THREAD

**Issue by kaustubh-d** [Seagate/cortx-prvsnr#294]
MTU for public data network gets reset to 1500 with preassigned IP case. 

Below code 
```
{% if pillar['cluster'][node]['network']['data_nw']['public_ip_addr'] %}
    - proto: none
    - ipaddr: {{ pillar['cluster'][node]['network']['data_nw']['public_ip_addr'] }}
    - mtu: 9000
{%- else %}
```
https://github.com/Seagate/cortx-prvsnr/blob/dev/srv/components/system/network/data/public/init.sls#L37-L41

set `mtu: 9000` for irrespective of explicitly setting public_ip_addr or not.

cc @johnbent @ipoddubnyy @ypise

**Comment by ypise** [comment]
Addressed with #637
