### ISSUE TITLE
csm.common.errors.CsmSetupError: error(4102): CSM init failed while auto deployment for dual node cluster (VMs)

### ISSUE THREAD

**Issue by imvenkip** [Seagate/cortx-prvsnr#571]
INFO    Oct  2 11:17:35 ]: Installing 'components.csm' for both nodes
ERROR: Minions returned with non-zero exit code
For detailed error logs, please see: /var/log/seagate/provisioner/auto-deploy-cortx.log

 

***** FAILED!!*****
Detailed error log is kept at: /var/log/seagate/provisioner/auto-deploy-cortx.log
You have mail in /var/spool/mail/root

-----
following error observed from deploy log file

ID: Stage - Init CSM
    Function: cmd.run
        Name: __slot__:salt:setup_conf.conf_cmd('/opt/seagate/cortx/csm/conf/setup.yaml', 'csm:init')
      Result: False
     Comment: Command "/usr/bin/csm_setup init" run
     Started: 05:18:14.562688
    Duration: 11324.353 ms
     Changes:
              ----------
              pid:
                  10601
              retcode:
                  1
              stderr:
                  Traceback (most recent call last):
                    File "csm/conf/setup.py", line 763, in init
                    File "csm/conf/setup.py", line 453, in _logrotate
                  TypeError: 'NoneType' object is not subscriptable
                  csm_setup command failed: Traceback (most recent call last):
                    File "/var/jenkins/workspace/Cortx-Releases/Cortx-1.0/CSM-Agent/csm/conf/csm_setup.py", line 87, in <module>
                    File "/var/jenkins/workspace/Cortx-Releases/Cortx-1.0/CSM-Agent/csm/conf/csm_setup.py", line 65, in process
                  csm.common.errors.CsmSetupError: error(4102): CSM init : Fail error(4102): csm_setup init failed. Error: 'NoneType' object is not subscriptable - None
              stdout:

**Comment by imvenkip** [comment]
And one more issue is observed. Before deployment, eth-1 and eth-2 have different ip addresses.  After deployment, both have same IP addresses in both nodes.


[root@ssc-vm-c-0983 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 56:6f:20:19:01:59 brd ff:ff:ff:ff:ff:ff
    inet 10.230.240.233/20 brd 10.230.255.255 scope global noprefixroute dynamic eth0
       valid_lft 406643sec preferred_lft 406643sec
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000
    link/ether 56:6f:20:19:01:5b brd ff:ff:ff:ff:ff:ff
    inet 192.168.13.94/20 brd 192.168.15.255 scope global dynamic eth1
       valid_lft 41957sec preferred_lft 41957sec
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000
    link/ether 56:6f:20:19:01:5c brd ff:ff:ff:ff:ff:ff
    inet 192.168.13.94/24 brd 192.168.13.255 scope global eth2
       valid_lft forever preferred_lft forever
You have new mail in /var/spool/mail/root
 

----------------

[root@ssc-vm-c-0982 /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 56:6f:20:19:01:6d brd ff:ff:ff:ff:ff:ff
    inet 10.230.240.224/20 brd 10.230.255.255 scope global noprefixroute dynamic eth0
       valid_lft 406695sec preferred_lft 406695sec
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000
    link/ether 56:6f:20:19:01:72 brd ff:ff:ff:ff:ff:ff
    inet 192.168.13.95/20 brd 192.168.15.255 scope global dynamic eth1
       valid_lft 38474sec preferred_lft 38474sec
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000
    link/ether 56:6f:20:19:01:81 brd ff:ff:ff:ff:ff:ff
    inet 192.168.13.95/24 brd 192.168.13.255 scope global eth2
       valid_lft forever preferred_lft forever
 


<https://teams.microsoft.com/l/message/19:402d571cd72b41b2ae50525aac03457d@thread.tacv2/1601658936127?tenantId=d466216a-c643-434a-9c2e-057448c17cbe&amp;groupId=7e2a2869-5847-4a65-9402-f4778c7b913e&amp;parentMessageId=1601643947878&amp;teamName=CORTX.All&amp;channelName=CORTX.Motr&amp;createdTime=1601658936127>

**Comment by ypise** [comment]
@imvenkip 
The IP issue seems to be like a configuration problem.
For CSM the issue should now be fixed in latest releases.
I'm closing this issue. If you still face these problems, do create a new one or feel free to re-open this issue.
