### ISSUE TITLE
Quick start guide link is broken

### ISSUE THREAD

**Issue by thavanathan** [Seagate/cortx-prvsnr#6022]
Quick start guide link given in the README is broken. I tried to locate it it in repo and unable to find.

[https://github.com/Seagate/cortx-prvsnr/blob/main/Cortx-ProvisionerQuickstartGuide.md](https://github.com/Seagate/cortx-prvsnr/blob/main/Cortx-ProvisionerQuickstartGuide.md)

**Comment by cortx-admin** [comment]
> Pritam Bhavsar commented in Jira Server:

No code changes are required, I have removed the QuickStart guide link from the Wiki page (home page) on the GitHub.

**Comment by cortx-admin** [comment]
> Pritam Bhavsar commented in Jira Server:

Closing as nothing else is required.
