### ISSUE TITLE
Broken link for Provisioner Quickstart Guide

### ISSUE THREAD

**Issue by osowski** [Seagate/cortx-prvsnr#6250]
The link included in the root README.md that points to the **CORTX-Provisioner Quickstart Guide** is broken and returns a 404. 

Location: https://github.com/Seagate/cortx-prvsnr/blob/main/README.md
Error:
```
Jump to the [CORTX-Provisioner Quickstart Guide](Cortx-ProvisionerQuickstartGuide.md) to set up CORTX-Provisioner. 
```

**Comment by cortx-admin** [comment]
> Pritam Bhavsar commented in Jira Server:

Closing the ticket as the broken link is now fixed.
