### ISSUE TITLE
Update sample config_vm.ini file with latest changes

### ISSUE THREAD

**Issue by gowthamchinna** [Seagate/cortx-prvsnr#903]
As per [VM-Provisioner-CLI-Commands](https://github.com/Seagate/cortx-prvsnr/wiki/Auto-Deploy-VM-Provisioner-CLI-Commands#sample-configini-for-single-node-vm) the config.ini contains `[storage]` block but in the [sample config.ini](https://github.com/Seagate/cortx-prvsnr/blob/main/pillar/samples/config_vm.ini)  it is not updated. So please update the sample configs for latest changes

Also please update the vm hostname with some generic  placeholder text

**Comment by ypise** [comment]
@gowthamchinna 
you can find the file [here](https://github.com/Seagate/cortx-prvsnr/blob/main/pillar/samples/config_vm.ini)
